# inflator.toml syntax documentation: https://github.com/inflated-goboscript/inflator#inflator
name = 'button_detector'
version = "v0.0.0"
username = "inflated-goboscript"

[dependencies]
assert = "assert"
